# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# theme: jekyll-theme-so-simple
# remote_theme: positivelydeadly/so-simple-theme

locale: en-US
title: "Positively Deadly Podcast"
description: "TBD"
baseurl: ""
url: "https://positivelydeadly.com"
email: "positivelydeadlypodcast@gmail.com"
pod_feed: "TBD"
itunes_url: "TBD"
newsletter_url: "TBD"
logo: "/images/TBD.png"
date_format: "%B %-d, %Y"
read_time: false
words_per_minute: # 200
mathjax: false
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "TBD"
disqus:
  shortname: "positivelydeadlypodcast"
twitter:
  username: "posdeadlypod"
google_site_verification: "TBD"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: 
  picture: 
  email: 
  twitter: 
  links:
    - title: 
      url: 
      icon: fab fa-twitter-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/posdeadlypod
    icon: fab fa-twitter-square
  - title: Newsletter
    url: TBD
    icon: fas fa-envelope-square
  - title: iTunes
    url: TBD
    icon: fab fa-itunes
  - title: Add to Podcatcher
    url: TBD
    icon: fas fa-plus-square
